// Member digests: the ~200-token "what is this Topic investigating, and where
// do its conclusions stand" blurb that the Research controller sees in its
// opening roster (spec §4.2.2).
//
// Two rules shape this file:
//
//  1. A digest is generated by the Research layer itself, with a SMALL model.
//     It is deliberately independent of the framework's context compaction —
//     whether `loadCompaction` has produced anything for that Topic is none of
//     this layer's business.
//  2. Digests go stale and are refreshed LAZILY. `staleDigests` (Task 3) makes
//     that decision without spending a model call; this file is the only place
//     that spends one. A Topic that hasn't moved costs nothing.

import type { ModelRouter } from "../../infra/llm/provider.ts";
import type { SessionEvent } from "../../framework/sessionState.ts";
import type { SessionRegistry } from "../../framework/sessionState.ts";
import type { ResearchMember } from "../../infra/db/sqliteEventStore.ts";
import { estimateTokens, type IndexedTurn } from "./retrieval.ts";
import { staleDigests, type MemberFacts } from "./memberContext.ts";
import { mapWithConcurrency } from "./concurrency.ts";

/** Model calls for digests run at most this many at a time (spec: concurrency cap 3). */
export const DIGEST_CONCURRENCY = 3;

/** Soft cap on how much history a single digest call is allowed to read. The
 *  most RECENT turns are kept — a digest describes where conclusions stand
 *  now, so the tail is the part that matters. */
const DIGEST_INPUT_BUDGET_TOKENS = 12_000;

/** What the store must offer for digest refresh. Narrower than the concrete
 *  SqliteEventStore so tests can supply a stub. */
export type DigestStore = {
  listResearchMembers(researchId: string): ResearchMember[];
  setMemberDigest(researchId: string, topicId: string, digest: string, digestThroughTurn: number): void;
};

/** What this module needs from SessionRegistry — the durable log of a Topic. */
export type TopicHistorySource = Pick<SessionRegistry, "loadEvents">;

/**
 * Projects a Topic's event log into turn-indexed user/reply pairs.
 *
 * The index unit is the TURN, anchored on the final reply that turn gave the
 * user (spec §4.3): `session_events.turn` already exists, so the turn number
 * itself is the id and no new index structure is needed. Turns with no reply
 * yet (in flight, or ended in an error) still appear, with an empty reply —
 * dropping them would silently renumber nothing but would hide that the user
 * asked something.
 *
 * Note this does not go through `projectChatHistory`: that projection is built
 * for the web client and discards the turn number, which is exactly the field
 * this layer indexes on.
 */
export function buildIndexedTurns(events: readonly SessionEvent[]): IndexedTurn[] {
  const byTurn = new Map<number, { user: string[]; finalReply?: string; lastReply?: string }>();

  for (const event of events) {
    if (event.is_sidechain) continue;
    if (event.kind !== "user_message" && event.kind !== "reply") continue;
    const bucket = byTurn.get(event.turn) ?? { user: [] };
    if (event.kind === "user_message") {
      bucket.user.push(String(event.payload.content ?? ""));
    } else {
      const content = String(event.payload.content ?? "");
      bucket.lastReply = content;
      if (event.payload.final === true) bucket.finalReply = content;
    }
    byTurn.set(event.turn, bucket);
  }

  return [...byTurn.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([turn, bucket]) => ({
      turn,
      user: bucket.user.join("\n"),
      reply: bucket.finalReply ?? bucket.lastReply ?? "",
    }));
}

/** Highest turn number present in a Topic's log — 0 for an untouched Topic. */
export function turnCountOf(turns: readonly IndexedTurn[]): number {
  return turns.reduce((max, t) => Math.max(max, t.turn), 0);
}

/** Keeps the most recent turns that fit the input budget. */
function tailWithinBudget(turns: readonly IndexedTurn[], budgetTokens: number): IndexedTurn[] {
  const kept: IndexedTurn[] = [];
  let used = 0;
  for (let i = turns.length - 1; i >= 0; i--) {
    const t = turns[i]!;
    const cost = estimateTokens(t.user) + estimateTokens(t.reply);
    if (kept.length > 0 && used + cost > budgetTokens) break;
    kept.unshift(t);
    used += cost;
  }
  return kept;
}

const DIGEST_SYSTEM = [
  "You are generating a \"Topic digest\" for an investment-research workspace.",
  "You are given the conversation history of a Topic (an ongoing research conversation).",
  "Write, in no more than 300 tokens, one blurb covering two things:",
  "1) what this Topic is investigating (a ticker / macro theme / question of interest);",
  "2) where its conclusions stand (confirmed judgments, unresolved disagreements, what to check next).",
  "Write only the blurb itself — no title, no bullet prefix, no pleasantries.",
  "If there is no conclusion yet, say so plainly — do not invent one.",
].join("\n");

/**
 * Generates one Topic's digest with a SMALL model.
 *
 * Returns "" for an empty history without calling a model: asking a model to
 * summarise a conversation that hasn't happened yields a confident description
 * of nothing.
 */
export async function generateDigest(turns: IndexedTurn[], modelRouter: ModelRouter): Promise<string> {
  if (turns.length === 0) return "";

  const transcript = tailWithinBudget(turns, DIGEST_INPUT_BUDGET_TOKENS)
    .map((t) => `[turn ${t.turn}]\nUser: ${t.user}\nReply: ${t.reply}`)
    .join("\n\n");

  const completion = await modelRouter.generate(
    [
      { role: "system", content: DIGEST_SYSTEM },
      { role: "user", content: `Conversation history:\n\n${transcript}\n\nPlease give the digest.` },
    ],
    { modelClass: "SMALL", temperature: 0.2, metadata: { mode: "research_digest" } },
  );

  return completion.text.trim();
}

export type DigestRefreshOutcome = {
  topicId: string;
  status: "refreshed" | "skipped" | "error";
  throughTurn: number;
  digest?: string;
  error?: string;
};

/**
 * Regenerates the digest of every member whose Topic has moved past
 * `digest_through_turn`, at most `DIGEST_CONCURRENCY` model calls at a time.
 *
 * One member's failure never fails the batch: a Research turn that can't
 * refresh one digest is still a usable turn, it just shows a slightly stale
 * blurb for that member.
 */
export async function refreshStaleDigests(
  researchId: string,
  store: DigestStore,
  sessions: TopicHistorySource,
  modelRouter: ModelRouter,
): Promise<DigestRefreshOutcome[]> {
  const members = store.listResearchMembers(researchId);
  if (members.length === 0) return [];

  const turnsByTopic = new Map<string, IndexedTurn[]>();
  await mapWithConcurrency(members, DIGEST_CONCURRENCY, async (member) => {
    turnsByTopic.set(member.topicId, buildIndexedTurns(await sessions.loadEvents(member.topicId)));
  });

  // staleDigests reads only topicId / turnCount / digestThroughTurn; the rest of
  // MemberFacts is the roster's concern (§4.2.1) and is filled in by the caller
  // that renders it, not here.
  const facts: Array<MemberFacts & { digestThroughTurn: number }> = members.map((member) => {
    const turns = turnsByTopic.get(member.topicId) ?? [];
    return {
      topicId: member.topicId,
      name: member.topicId,
      leadSymbol: null,
      chartSymbols: [],
      turnCount: turnCountOf(turns),
      lastActivityMs: 0,
      digest: member.digest,
      seenThroughTurn: member.seenThroughTurn,
      digestThroughTurn: member.digestThroughTurn,
    };
  });

  const stale = staleDigests(facts);

  return mapWithConcurrency(stale, DIGEST_CONCURRENCY, async (topicId): Promise<DigestRefreshOutcome> => {
    const turns = turnsByTopic.get(topicId) ?? [];
    const throughTurn = turnCountOf(turns);
    try {
      const digest = await generateDigest(turns, modelRouter);
      if (!digest) return { topicId, status: "skipped", throughTurn };
      store.setMemberDigest(researchId, topicId, digest, throughTurn);
      return { topicId, status: "refreshed", throughTurn, digest };
    } catch (error) {
      return { topicId, status: "error", throughTurn, error: error instanceof Error ? error.message : String(error) };
    }
  });
}
